name: Publish Addon

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-addon
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: "latest"
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox
          rm .output/*-sources.zip

      - name: Generate release metadata
        id: metadata
        run: |
          # 动态生成发布标题，格式：Nightly Build (YYYY-MM-DD)
          echo "release_name=Nightly Build ($(date +'%Y-%m-%d'))" >> $GITHUB_OUTPUT
          # 获取短格式的 commit hash
          echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          make_latest: true
          overwrite: true
          name: ${{ steps.metadata.outputs.release_name }}
          tag_name: nightly
          body_path: .github/release.md
          files: |
            .output/addon-*.zip
