name: Publish Addon

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-addon
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: "latest"
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox
          rm .output/*-sources.zip

      - name: Generate release metadata
        id: metadata
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "Release ${{ github.ref_name }}"
            echo "prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "Prerelease nightly"
            echo "prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=Nightly Build ($(date +'%Y-%m-%d'))" >> $GITHUB_OUTPUT
            echo "tag_name=nightly" >> $GITHUB_OUTPUT
          fi

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.metadata.outputs.prerelease }}
          make_latest: ${{ steps.metadata.outputs.prerelease != 'true' }}
          overwrite_files: ${{ steps.metadata.outputs.prerelease == 'true' }}
          name: ${{ steps.metadata.outputs.release_name }}
          tag_name: ${{ steps.metadata.outputs.tag_name }}
          files: |
            .output/addon-*.zip
